services:
  cloud_chatops:
    image: harbor.stfc.ac.uk/stfc-cloud/cloud-chatops:3.3.0
    volumes:
      - /etc/chatops/secrets/:/usr/src/app/cloud_chatops/secrets/
      - /etc/chatops/config/:/usr/src/app/cloud_chatops/config/
